"""Rebuild the current figure and supplementary-table outputs.

This wrapper calls the adopted plotting entry points used for the final
figure-only GitHub release. Figure 1 is supplied as final artwork under
``outputs/main_figures`` and is not regenerated by these data-plotting scripts.
"""

from __future__ import annotations

from figures.plot_supplementary_figures_s3_s6 import main as build_supplementary_s3_s6
from figures.build_supplementary_tables import main as build_supplementary_tables
from figures.plot_figure_2 import build_fig2
from figures.plot_figures_3_4 import build_fig3, build_fig4
from figures.plot_figures_5_7 import build_fig5, build_fig6, build_fig7
from figures.plot_supplementary_figure_s2 import main as build_supplementary_s2


def main() -> None:
    build_fig2()
    build_fig3()
    build_fig4()
    build_fig5()
    build_fig6()
    build_fig7()
    build_supplementary_s2()
    build_supplementary_s3_s6()
    build_supplementary_tables()
    print("Finished rebuilding current main figures, supplementary figures and supplementary tables.")


if __name__ == "__main__":
    main()


